# Initial A and B matrixes generation

In [37]:
import numpy as np

K, L, T = 3, 3, 2 # A, B submatrixies
p = 29 # field (finite or np.inf)

bound = 12 # values boundaries

# sizes: size_A * width_AB and width_AB * size_B => result size_A * size_B
width_AB = 3
size_A, size_B = 9, 9

assert size_A % K == 0, 'Please, use multiples of each other numbers'
assert size_B % L == 0, 'Please, use multiples of each other numbers'

A = np.matrix(np.random.randint(0, bound, (width_AB, size_A))).astype(object).T % p
B = np.matrix(np.random.randint(0, bound, (width_AB, size_B))).astype(object) % p

print('Matrices A, B have been generated')
display('A = ', A)
display('B = ', B)

Matrices A, B have been generated


'A = '

matrix([[9, 6, 7],
        [9, 5, 8],
        [0, 2, 1],
        [2, 4, 9],
        [10, 8, 11],
        [0, 5, 8],
        [8, 7, 9],
        [11, 5, 7],
        [3, 3, 9]], dtype=object)

'B = '

matrix([[0, 8, 7, 9, 10, 5, 9, 3, 11],
        [11, 2, 3, 4, 3, 3, 7, 3, 10],
        [7, 10, 1, 10, 4, 11, 10, 9, 1]], dtype=object)

# Regular A and B multiplication

In [38]:
REG_MAT_MUL = A @ B % p
REG_MAT_MUL

matrix([[28, 9, 1, 1, 20, 24, 19, 21, 21],
        [24, 17, 28, 7, 21, 3, 22, 27, 12],
        [0, 14, 7, 18, 10, 17, 24, 15, 21],
        [20, 27, 6, 8, 10, 5, 20, 12, 13],
        [20, 3, 18, 0, 23, 21, 24, 8, 27],
        [24, 3, 23, 13, 18, 16, 28, 0, 0],
        [24, 23, 28, 16, 21, 15, 8, 10, 22],
        [17, 23, 12, 15, 8, 2, 1, 24, 4],
        [9, 4, 10, 13, 17, 7, 22, 12, 14]], dtype=object)

# Genearating A_k, B_l, k = 1...K, l = 1...L submatrixes

In [39]:
# A submatrices
print('Submatrices A_i have been generated')
A_ = np.zeros([K, int(size_A / K), width_AB], dtype= object)
for i in range(K):
    A_[i] = np.split(A, K, axis = 0)[i] % p
display('A = ', A_)

# B submatrices
print('Submatrices B_i have been generated')
B_ = np.zeros([L, width_AB, int(size_B / L)], dtype= object)
for i in range(L):
    B_[i] = np.split(B, L, axis = 1)[i] % p
display('B = ', B_)

Submatrices A_i have been generated


'A = '

array([[[9, 6, 7],
        [9, 5, 8],
        [0, 2, 1]],

       [[2, 4, 9],
        [10, 8, 11],
        [0, 5, 8]],

       [[8, 7, 9],
        [11, 5, 7],
        [3, 3, 9]]], dtype=object)

Submatrices B_i have been generated


'B = '

array([[[0, 8, 7],
        [11, 2, 3],
        [7, 10, 1]],

       [[9, 10, 5],
        [4, 3, 3],
        [10, 4, 11]],

       [[9, 3, 11],
        [7, 3, 10],
        [10, 9, 1]]], dtype=object)

# Multiplication using A_k, B_l parts

In [40]:
result = np.zeros([size_A, size_B], dtype= object) # we know size to be calculated
for i in range(0, A_.shape[0], 1): # for each partial A matrix
    for j in range(0, B_.shape[0], 1): # for each partial B matrix
        delta_A, delta_B = int(size_A / K), int(size_B / L)
        # calculate each result A_[i] @ B_[j] separately
        result[delta_A*i:delta_A*(i+1), delta_B*j:delta_B*(j+1)] = A_[i] @ B_[j] % p
PARTED_MAT_MUL = result
PARTED_MAT_MUL % p

array([[28, 9, 1, 1, 20, 24, 19, 21, 21],
       [24, 17, 28, 7, 21, 3, 22, 27, 12],
       [0, 14, 7, 18, 10, 17, 24, 15, 21],
       [20, 27, 6, 8, 10, 5, 20, 12, 13],
       [20, 3, 18, 0, 23, 21, 24, 8, 27],
       [24, 3, 23, 13, 18, 16, 28, 0, 0],
       [24, 23, 28, 16, 21, 15, 8, 10, 22],
       [17, 23, 12, 15, 8, 2, 1, 24, 4],
       [9, 4, 10, 13, 17, 7, 22, 12, 14]], dtype=object)

# Check if regular mat.mul equals to partial mat.mul

In [41]:
PARTED_MAT_MUL == REG_MAT_MUL

matrix([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

# Encoding procedure

### S_t, R_t submatrices generation, t = 1...T

In [42]:
# S submatrices
print('Submatrices R_i have been generated')
R_ = np.zeros([T, int(size_A / K), width_AB], dtype= object)
for i in range(T):
    R_[i] = np.matrix(np.random.randint(1, bound, (int(size_A / K), width_AB))) % p
display('R_ = ', R_)

# R submatrices
print('Submatrices S_i have been generated')
S_ = np.zeros([T, width_AB, int(size_B / L)], dtype= object)
for i in range(T):
    S_[i] = np.matrix(np.random.randint(1, bound, (width_AB, int(size_B / L)))) % p
display('S_ = ', S_)

Submatrices R_i have been generated


'R_ = '

array([[[11, 10, 2],
        [4, 3, 1],
        [10, 5, 2]],

       [[7, 8, 8],
        [3, 11, 8],
        [10, 9, 10]]], dtype=object)

Submatrices S_i have been generated


'S_ = '

array([[[7, 6, 4],
        [7, 10, 8],
        [2, 4, 5]],

       [[5, 7, 11],
        [3, 6, 1],
        [11, 3, 3]]], dtype=object)

# Vector of coefficients of f(x) and g(x): A1,A2,A3,R1,R2...

In [43]:
F_X = np.vstack((A_, R_)) # vertical concatination (F_X = A1,A2,A3,R1,R2)
G_X = np.vstack((B_, S_)) # vertical concatination (G_X = B1,B2,B3,S1,S2)

display('F_X = ', F_X)
display('G_X = ', G_X)

'F_X = '

array([[[9, 6, 7],
        [9, 5, 8],
        [0, 2, 1]],

       [[2, 4, 9],
        [10, 8, 11],
        [0, 5, 8]],

       [[8, 7, 9],
        [11, 5, 7],
        [3, 3, 9]],

       [[11, 10, 2],
        [4, 3, 1],
        [10, 5, 2]],

       [[7, 8, 8],
        [3, 11, 8],
        [10, 9, 10]]], dtype=object)

'G_X = '

array([[[0, 8, 7],
        [11, 2, 3],
        [7, 10, 1]],

       [[9, 10, 5],
        [4, 3, 3],
        [10, 4, 11]],

       [[9, 3, 11],
        [7, 3, 10],
        [10, 9, 1]],

       [[7, 6, 4],
        [7, 10, 8],
        [2, 4, 5]],

       [[5, 7, 11],
        [3, 6, 1],
        [11, 3, 3]]], dtype=object)

# Alpha and beta arrays: alphas(K+T), betas(L+T), N servers

In [44]:
# GASP BIG (N calculation)
def get_N_GB(K, L, T):
    N = 0
    if L <= K:
        if T < K:
            N = (K + T) * (L + 1) - 1
        elif T >= K:
            N = 2 * K * L + 2 * T - 1
    if L > K:
        if T < L:
            N = (L + T) * (K + 1) - 1
        elif T >= L:
            N = 2 * K * L + 2 * T - 1
    return N

# GASP SMALL (N calculation)
def get_N_GS(K, L, T):
    N = 0
    if K <= L:
        if L == 1 and T < K:
            N = 2*K + T*T
        elif L == 1 and T >= K:
            N = K*T + K + T
        elif L >=2 and T == 1 and T < K:
            N = K*L + K + L
        elif L >=2 and T >=2 and T < K:
            N = K*L + K + L + T*T + T - 3
        elif L >= 2 and K <= T and T <= K * (L - 1) + 1:
            N = K*L + K*T + L + 2*T - 3 - ((T - 2) / K)
        elif L >= 2 and T >= K * (L - 1) + 1:
            N = 2*K*L + K*T - K + T
    if K > L:
        if K == 1 and T < L:
            N = 2*L + T*T
        elif K == 1 and T >= L:
            N = L*T + L + T
        elif K >=2 and T == 1 and T < L:
            N = K*L + K + L
        elif K >=2 and T >= 2 and T < L:
            N = K*L + K + L + T*T + T - 3
        elif K >= 2 and L <= T and T <= L * (K - 1) + 1:
            N = K*L + L*T + K + 2*T - 3 - ((T - 2) / L)
        elif K >= 2 and T >= L * (K - 1) + 1:
            N = 2*K*L + L*T - L + T
    return N

# the set of degrees
def GASP_big(K, L, T):
    if K >= L:
        a = np.zeros([K + T], dtype= object)
        b = np.zeros([L + T], dtype= object)
        for k in range(0, K, 1):
            a[k] = k
        for t in range(0, T, 1):
            a[K + t] = K * L + t

        for l in range(0, L, 1):
            b[l] = K * l
        for t in range(0, T, 1):
            b[L + t] = K * L + t

    if K < L:
        a = np.zeros([L + T], dtype= object)
        b = np.zeros([K + T], dtype= object)
        
        for l in range(0, L, 1):
            a[l] = K * l
        for t in range(0, T, 1):
            a[L + t] = K * L + t
        
        for k in range(0, K, 1):
            b[k] = k
        for t in range(0, T, 1):
            b[K + t] = K * L + t

    return a, b

# the set of degrees
def GASP_small(K, L, T):
    if K <= L:
        a = np.zeros([K + T])
        b = np.zeros([L + T])
        for k in range(0, K, 1):
            a[k] = k
        for t in range(0, T, 1):
            a[K + t] = K * L + K * t

        for l in range(0, L, 1):
            b[l] = K * l
        for t in range(0, T, 1):
            b[L + t] = K * L + t

    if K > L:
        a = np.zeros([L + T])
        b = np.zeros([K + T])

        for l in range(0, L, 1):
            a[l] = K * l
        for t in range(0, T, 1):
            a[L + t] = K * L + t
        
        for k in range(0, K, 1):
            b[k] = k
        for t in range(0, T, 1):
            b[K + t] = K * L + K * t

    return a, b

def GASP(K, L, T):
    min_KL = np.minimum(K, L)
    
    if T < min_KL:
        alp, bet = GASP_small(K, L, T)
        N = get_N_GS(K, L, T)
        print('T < min(K,L) - GASP_small, N = ', N)
        
    if T >= min_KL:
        alp, bet = GASP_big(K, L, T)
        N = get_N_GB(K, L, T)
        print('T >= min(K,L) - GASP_big, N = ', N)
        
    return alp, bet, N

# Print N, alpha and beta sets corresponding current K,L,T

In [45]:
alphas, betas, N = GASP(K = K, L = L, T = T)
display('alphas = ', alphas)
display('betas = ', betas)

T < min(K,L) - GASP_small, N =  18


'alphas = '

array([ 0.,  1.,  2.,  9., 12.])

'betas = '

array([ 0.,  3.,  6.,  9., 10.])

# Let's build the degree table

In [46]:
degree_table = np.zeros([alphas.shape[0], betas.shape[0]], dtype= object)

for i in range(alphas.shape[0]):
    for j in range(betas.shape[0]):
        degree_table[i,j] = alphas[i] + betas[j]
        
display('degree_table =', degree_table)

'degree_table ='

array([[0.0, 3.0, 6.0, 9.0, 10.0],
       [1.0, 4.0, 7.0, 10.0, 11.0],
       [2.0, 5.0, 8.0, 11.0, 12.0],
       [9.0, 12.0, 15.0, 18.0, 19.0],
       [12.0, 15.0, 18.0, 21.0, 22.0]], dtype=object)

# The set of unique polnom's powers

In [47]:
J = np.unique(degree_table.reshape([degree_table.size]))

print('All degrees in table = ', J)

All degrees in table =  [0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 15.0 18.0 19.0
 21.0 22.0]


# Set of x points for N servers

In [48]:
x = np.arange(1, N+1).reshape([N,1]) @ np.ones([1,K+T], dtype= object)
x

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9],
       [10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12],
       [13, 13, 13, 13, 13],
       [14, 14, 14, 14, 14],
       [15, 15, 15, 15, 15],
       [16, 16, 16, 16, 16],
       [17, 17, 17, 17, 17],
       [18, 18, 18, 18, 18]], dtype=object)

# Set of alphas and betas for N servers

In [49]:
alfa = np.ones([N,1], dtype= object) @ alphas.reshape([1,alphas.size])
beta = np.ones([N,1], dtype= object) @ betas.reshape([1,betas.size])
alfa

array([[0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0],
       [0.0, 1.0, 2.0, 9.0, 12.0]], dtype=object)

# Set of x^alphas and x^betas for N servers

In [50]:
f_x_coefs = x**alfa % p
g_x_coefs = x**beta % p
f_x_coefs

array([[1.0, 1.0, 1.0, 1.0, 1.0],
       [1.0, 2.0, 4.0, 19.0, 7.0],
       [1.0, 3.0, 9.0, 21.0, 16.0],
       [1.0, 4.0, 16.0, 13.0, 20.0],
       [1.0, 5.0, 25.0, 4.0, 7.0],
       [1.0, 6.0, 7.0, 22.0, 25.0],
       [1.0, 7.0, 20.0, 20.0, 16.0],
       [1.0, 8.0, 6.0, 15.0, 24.0],
       [1.0, 9.0, 23.0, 6.0, 24.0],
       [1.0, 10.0, 13.0, 18.0, 20.0],
       [1.0, 11.0, 5.0, 2.0, 23.0],
       [1.0, 12.0, 28.0, 12.0, 1.0],
       [1.0, 13.0, 24.0, 5.0, 23.0],
       [1.0, 14.0, 22.0, 3.0, 25.0],
       [1.0, 15.0, 22.0, 26.0, 25.0],
       [1.0, 16.0, 24.0, 24.0, 23.0],
       [1.0, 17.0, 28.0, 17.0, 1.0],
       [1.0, 18.0, 5.0, 27.0, 23.0]], dtype=object)

# Polynoms f(x) and g(x) for each server (separate values, not sum)

In [51]:
m = int(size_A / K) # size of submatrixes A
n = int(size_B / L) # size of submatrixes B

In [52]:
f_x = np.zeros([N, alphas.size, m,n], dtype= object)
g_x = np.zeros([N, betas.size, m,n], dtype= object)

for i in range(N):
    for j in range(5):
        f_x[i,j] = f_x_coefs[i,j] * F_X[j] % p
        g_x[i,j] = g_x_coefs[i,j] * G_X[j] % p
        
display('f_x[i] = ', f_x[1].astype('int'))

'f_x[i] = '

array([[[ 9,  6,  7],
        [ 9,  5,  8],
        [ 0,  2,  1]],

       [[ 4,  8, 18],
        [20, 16, 22],
        [ 0, 10, 16]],

       [[ 3, 28,  7],
        [15, 20, 28],
        [12, 12,  7]],

       [[ 6, 16,  9],
        [18, 28, 19],
        [16,  8,  9]],

       [[20, 27, 27],
        [21, 19, 27],
        [12,  5, 12]]])

# Polynoms f(x) and g(x) for each server - sum result along 0 axis: f(a_n) and g(a_n), a_n = 1...N 

In [53]:
f_x_i = np.zeros([N,m,n], dtype= object)
g_x_i = np.zeros([N,m,n], dtype= object)
for i in range(N):
    f_x_i[i] = f_x[i].sum(axis = 0) % p
    g_x_i[i] = g_x[i].sum(axis = 0) % p

display('f_x_i[i] = ', f_x_i[1].astype('int'))
display('f_x_i[i]*g_x_i[i] = ', (f_x_i[1]*g_x_i[1]))

'f_x_i[i] = '

array([[13, 27, 10],
       [25,  1, 17],
       [11,  8, 16]])

'f_x_i[i]*g_x_i[i] = '

array([[182.0, 594.0, 270.0],
       [325.0, 27.0, 272.0],
       [253.0, 200.0, 224.0]], dtype=object)

# Server calculations imitation: h(a_n) = f(a_n) * g(a_n), a_n = 1...N

In [105]:
h_i = np.zeros([N,m,n], dtype= object)
for server in range(N):
    h_i[server] = (f_x_i[server] @ g_x_i[server]) % p
    
# h_i = h_i.reshape([N,1])
display('h_i = ', h_i)

'h_i = '

array([[[5.0, 16.0, 0.0],
        [25.0, 2.0, 12.0],
        [19.0, 25.0, 16.0]],

       [[9.0, 18.0, 24.0],
        [0.0, 16.0, 1.0],
        [17.0, 17.0, 11.0]],

       [[11.0, 23.0, 10.0],
        [24.0, 25.0, 0.0],
        [28.0, 21.0, 23.0]],

       [[3.0, 16.0, 14.0],
        [8.0, 7.0, 19.0],
        [13.0, 4.0, 25.0]],

       [[2.0, 28.0, 21.0],
        [18.0, 14.0, 16.0],
        [15.0, 1.0, 16.0]],

       [[25.0, 27.0, 17.0],
        [4.0, 25.0, 9.0],
        [4.0, 12.0, 12.0]],

       [[16.0, 11.0, 2.0],
        [24.0, 24.0, 15.0],
        [12.0, 8.0, 4.0]],

       [[16.0, 13.0, 2.0],
        [4.0, 17.0, 14.0],
        [27.0, 12.0, 24.0]],

       [[12.0, 3.0, 14.0],
        [26.0, 28.0, 0.0],
        [6.0, 11.0, 14.0]],

       [[5.0, 24.0, 19.0],
        [4.0, 8.0, 5.0],
        [18.0, 3.0, 2.0]],

       [[0.0, 9.0, 1.0],
        [6.0, 17.0, 2.0],
        [15.0, 5.0, 11.0]],

       [[27.0, 11.0, 6.0],
        [19.0, 22.0, 11.0],
        [4.0, 14.0, 22.0]],

      

# Decoding using inverse Vandermond matrix

In [106]:
# find all numbers from zero to max value in the degree table
numbers_range = np.arange(0, max(J)+1).astype('object')
print('Range 0 to max power =', numbers_range)

# find all numbers from the degree table
degree_range_in_table = J
print('All powers in table = ', degree_range_in_table)

# find all numbers from the numbers_range which are not in the degree table (to delete)
degree_to_delete = np.delete(numbers_range, obj = degree_range_in_table.astype(np.int64), axis = 0)
print('Powers with zero coefficients = ', degree_to_delete)

Range 0 to max power = [0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0
 16.0 17.0 18.0 19.0 20.0 21.0 22.0]
All powers in table =  [0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 15.0 18.0 19.0
 21.0 22.0]
Powers with zero coefficients =  [13.0 14.0 16.0 17.0 20.0]


# Vandermond matrix generation

In [107]:
vand = np.zeros([N,int(max(J)+1)], dtype= object)
for a in range(1, N+1):
    vand[a-1] = np.array([a**x for x in range(int(max(J)+1))], dtype= object) % p
vand

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 2, 4, 8, 16, 3, 6, 12, 24, 19, 9, 18, 7, 14, 28, 27, 25, 21,
        13, 26, 23, 17, 5],
       [1, 3, 9, 27, 23, 11, 4, 12, 7, 21, 5, 15, 16, 19, 28, 26, 20, 2,
        6, 18, 25, 17, 22],
       [1, 4, 16, 6, 24, 9, 7, 28, 25, 13, 23, 5, 20, 22, 1, 4, 16, 6,
        24, 9, 7, 28, 25],
       [1, 5, 25, 9, 16, 22, 23, 28, 24, 4, 20, 13, 7, 6, 1, 5, 25, 9,
        16, 22, 23, 28, 24],
       [1, 6, 7, 13, 20, 4, 24, 28, 23, 22, 16, 9, 25, 5, 1, 6, 7, 13,
        20, 4, 24, 28, 23],
       [1, 7, 20, 24, 23, 16, 25, 1, 7, 20, 24, 23, 16, 25, 1, 7, 20, 24,
        23, 16, 25, 1, 7],
       [1, 8, 6, 19, 7, 27, 13, 17, 20, 15, 4, 3, 24, 18, 28, 21, 23, 10,
        22, 2, 16, 12, 9],
       [1, 9, 23, 4, 7, 5, 16, 28, 20, 6, 25, 22, 24, 13, 1, 9, 23, 4, 7,
        5, 16, 28, 20],
       [1, 10, 13, 14, 24, 8, 22, 17, 25, 18, 6, 2, 20, 26, 28, 19, 16,
        15, 5, 21, 7, 12, 4],
       [1, 11,

# Cut degrees with zero coefficients for Vandermond matrix

In [108]:
cut_vand = np.delete(vand, obj = degree_to_delete.astype(np.int64), axis = 1) # delete places with zero coeffs of x_i
print(cut_vand.shape)
cut_vand

(18, 18)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 4, 8, 16, 3, 6, 12, 24, 19, 9, 18, 7, 27, 13, 26, 17, 5],
       [1, 3, 9, 27, 23, 11, 4, 12, 7, 21, 5, 15, 16, 26, 6, 18, 17, 22],
       [1, 4, 16, 6, 24, 9, 7, 28, 25, 13, 23, 5, 20, 4, 24, 9, 28, 25],
       [1, 5, 25, 9, 16, 22, 23, 28, 24, 4, 20, 13, 7, 5, 16, 22, 28, 24],
       [1, 6, 7, 13, 20, 4, 24, 28, 23, 22, 16, 9, 25, 6, 20, 4, 28, 23],
       [1, 7, 20, 24, 23, 16, 25, 1, 7, 20, 24, 23, 16, 7, 23, 16, 1, 7],
       [1, 8, 6, 19, 7, 27, 13, 17, 20, 15, 4, 3, 24, 21, 22, 2, 12, 9],
       [1, 9, 23, 4, 7, 5, 16, 28, 20, 6, 25, 22, 24, 9, 7, 5, 28, 20],
       [1, 10, 13, 14, 24, 8, 22, 17, 25, 18, 6, 2, 20, 19, 5, 21, 12, 4],
       [1, 11, 5, 26, 25, 14, 9, 12, 16, 2, 22, 10, 23, 18, 4, 15, 17,
        13],
       [1, 12, 28, 17, 1, 12, 28, 17, 1, 12, 28, 17, 1, 17, 28, 17, 12,
        28],
       [1, 13, 24, 22, 25, 6, 20, 28, 16, 5, 7, 4, 23, 13, 25, 6, 28, 16],
       [1, 14, 22, 18, 20, 19, 

# Find the inverse Vandermond matrix in the finite field

In [109]:
from sympy import Matrix, pprint

In [110]:
VAND = Matrix(cut_vand) # change type for our cut_vand matrix

In [111]:
pprint(VAND)

⎡1  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 ⎤
⎢                                                                     ⎥
⎢1  2   4   8   16  3   6   12  24  19  9   18  7   27  13  26  17  5 ⎥
⎢                                                                     ⎥
⎢1  3   9   27  23  11  4   12  7   21  5   15  16  26  6   18  17  22⎥
⎢                                                                     ⎥
⎢1  4   16  6   24  9   7   28  25  13  23  5   20  4   24  9   28  25⎥
⎢                                                                     ⎥
⎢1  5   25  9   16  22  23  28  24  4   20  13  7   5   16  22  28  24⎥
⎢                                                                     ⎥
⎢1  6   7   13  20  4   24  28  23  22  16  9   25  6   20  4   28  23⎥
⎢                                                                     ⎥
⎢1  7   20  24  23  16  25  1   7   20  24  23  16  7   23  16  1   7 ⎥
⎢                                                               

In [112]:
VAND = VAND.inv_mod(p) # find inverse matrix in the finite field

In [114]:
VAND

Matrix([
[12,  7, 17,  8, 22, 17,  4, 23, 21, 26, 16,  5, 18, 12, 27, 12, 22, 22],
[ 1,  3, 27, 13, 27, 19, 18, 19, 24,  2, 27, 27, 11, 19,  2, 17,  4,  1],
[10, 11,  6, 11,  7, 12, 21,  7, 15, 26, 23, 13,  7, 21, 14, 21,  3,  4],
[24,  8,  4, 25,  2, 20,  3, 15, 11, 22, 19, 22, 26, 17, 20, 28, 13, 11],
[25,  6,  2,  1, 11,  1, 23, 23, 17,  2, 10, 11, 10,  4,  4, 21, 25,  7],
[13,  4, 13,  1,  5,  7, 20, 19,  5, 24,  5, 20,  0, 20,  5, 14, 27,  1],
[ 4,  8,  9, 24, 12,  4,  3, 19,  2,  2,  3, 23, 16, 28, 11, 22, 10,  3],
[20, 19, 17, 17,  1, 27, 15, 16, 16, 12, 25, 18, 11,  9, 19, 23,  7, 18],
[ 4,  3, 20, 26, 15, 14, 13,  8, 24, 25, 15, 15, 15, 26, 27, 19, 16,  5],
[ 3, 13, 23,  9, 17, 25,  2,  1, 24, 21, 28, 10, 25, 17,  7,  8, 22,  6],
[14, 24, 28, 17,  2, 20, 28, 27,  3, 10, 11,  3,  5, 12, 11,  5, 23, 18],
[27, 20, 25,  0, 15,  5, 20, 23, 18,  5, 16,  6,  4, 16, 23, 24, 26, 17],
[25, 10, 21, 12, 17, 25, 20,  5,  3,  2, 13, 19, 23,  1, 11,  6, 20, 28],
[ 0,  8, 25, 25, 15, 15, 28, 

In [115]:
vand_inv = np.array(VAND).astype(np.int64) # convert to numpy array

In [116]:
vand_inv

array([[12,  7, 17,  8, 22, 17,  4, 23, 21, 26, 16,  5, 18, 12, 27, 12,
        22, 22],
       [ 1,  3, 27, 13, 27, 19, 18, 19, 24,  2, 27, 27, 11, 19,  2, 17,
         4,  1],
       [10, 11,  6, 11,  7, 12, 21,  7, 15, 26, 23, 13,  7, 21, 14, 21,
         3,  4],
       [24,  8,  4, 25,  2, 20,  3, 15, 11, 22, 19, 22, 26, 17, 20, 28,
        13, 11],
       [25,  6,  2,  1, 11,  1, 23, 23, 17,  2, 10, 11, 10,  4,  4, 21,
        25,  7],
       [13,  4, 13,  1,  5,  7, 20, 19,  5, 24,  5, 20,  0, 20,  5, 14,
        27,  1],
       [ 4,  8,  9, 24, 12,  4,  3, 19,  2,  2,  3, 23, 16, 28, 11, 22,
        10,  3],
       [20, 19, 17, 17,  1, 27, 15, 16, 16, 12, 25, 18, 11,  9, 19, 23,
         7, 18],
       [ 4,  3, 20, 26, 15, 14, 13,  8, 24, 25, 15, 15, 15, 26, 27, 19,
        16,  5],
       [ 3, 13, 23,  9, 17, 25,  2,  1, 24, 21, 28, 10, 25, 17,  7,  8,
        22,  6],
       [14, 24, 28, 17,  2, 20, 28, 27,  3, 10, 11,  3,  5, 12, 11,  5,
        23, 18],
       [27, 20, 25,  

# Check if inverse transform is correct

In [117]:
vand_inv @ cut_vand % p

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [157]:
 cut_vand @ vand_inv % p

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

# Data restoring

In [158]:
# since the product h has size m*n, the inverse Vandermond matrix should have same size
multivand = np.zeros([N,N,m,n])

for i in range(N):
    for j in range(N):
        multivand[i,j,:,:] = vand_inv[i,j] % p
        
multivand

array([[[[12., 12., 12.],
         [12., 12., 12.],
         [12., 12., 12.]],

        [[ 7.,  7.,  7.],
         [ 7.,  7.,  7.],
         [ 7.,  7.,  7.]],

        [[17., 17., 17.],
         [17., 17., 17.],
         [17., 17., 17.]],

        ...,

        [[12., 12., 12.],
         [12., 12., 12.],
         [12., 12., 12.]],

        [[22., 22., 22.],
         [22., 22., 22.],
         [22., 22., 22.]],

        [[22., 22., 22.],
         [22., 22., 22.],
         [22., 22., 22.]]],


       [[[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 3.,  3.,  3.],
         [ 3.,  3.,  3.],
         [ 3.,  3.,  3.]],

        [[27., 27., 27.],
         [27., 27., 27.],
         [27., 27., 27.]],

        ...,

        [[17., 17., 17.],
         [17., 17., 17.],
         [17., 17., 17.]],

        [[ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]],


       [

# Find coefficients using inverse Vandermond matrix and product h

In [159]:
C = np.zeros([N,m,n],dtype = object)

for i in range(m):
    for j in range(n):
        C[:,i,j] = multivand[:,:,i,j] @ h_i[:,i,j] % p
C

array([[[28.0, 9.0, 1.0],
        [24.0, 17.0, 28.0],
        [0.0, 14.0, 7.0]],

       [[20.0, 27.0, 6.0],
        [20.0, 3.0, 18.0],
        [24.0, 3.0, 23.0]],

       [[24.0, 23.0, 28.0],
        [17.0, 23.0, 12.0],
        [9.0, 4.0, 10.0]],

       [[1.0, 20.0, 24.0],
        [7.0, 21.0, 3.0],
        [18.0, 10.0, 17.0]],

       [[8.0, 10.0, 5.0],
        [0.0, 23.0, 21.0],
        [13.0, 18.0, 16.0]],

       [[16.0, 21.0, 15.0],
        [15.0, 8.0, 2.0],
        [13.0, 17.0, 7.0]],

       [[19.0, 21.0, 21.0],
        [22.0, 27.0, 12.0],
        [24.0, 15.0, 21.0]],

       [[20.0, 12.0, 13.0],
        [24.0, 8.0, 27.0],
        [28.0, 0.0, 0.0]],

       [[8.0, 10.0, 22.0],
        [1.0, 24.0, 4.0],
        [22.0, 12.0, 14.0]],

       [[11.0, 9.0, 25.0],
        [9.0, 10.0, 9.0],
        [27.0, 18.0, 21.0]],

       [[26.0, 5.0, 8.0],
        [6.0, 11.0, 26.0],
        [10.0, 10.0, 27.0]],

       [[12.0, 16.0, 12.0],
        [2.0, 5.0, 9.0],
        [18.0, 22.0, 23.0]],

 

# Combine this result in one matrix to compare

In [160]:
step = 0
result = np.zeros([9, 9])
for i in range(m):
    for j in range(n):
        result[3*j:3*(j+1), 3*i:3*(i+1)] =  C[step]
        step += 1
result

array([[28.,  9.,  1.,  1., 20., 24., 19., 21., 21.],
       [24., 17., 28.,  7., 21.,  3., 22., 27., 12.],
       [ 0., 14.,  7., 18., 10., 17., 24., 15., 21.],
       [20., 27.,  6.,  8., 10.,  5., 20., 12., 13.],
       [20.,  3., 18.,  0., 23., 21., 24.,  8., 27.],
       [24.,  3., 23., 13., 18., 16., 28.,  0.,  0.],
       [24., 23., 28., 16., 21., 15.,  8., 10., 22.],
       [17., 23., 12., 15.,  8.,  2.,  1., 24.,  4.],
       [ 9.,  4., 10., 13., 17.,  7., 22., 12., 14.]])

# Lets compare achieved result with regular mat.mul
It's work!

In [156]:
REG_MAT_MUL == result

matrix([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True]])